# INCIDENT: CrashLoopBackOff - Missing Environment Variable
#
# Scenario: Deploy demo-api WITHOUT the required DATABASE_URL secret
# Expected: Pod enters CrashLoopBackOff, container exits with code 1
#
# AEGIS Expected Detection:
#   Root Cause: Missing required environment variable DATABASE_URL
#   Severity: HIGH
#   Fix: Add secretRef for demo-api-secrets
#
# Usage:
#   kubectl apply -f crashloop-missing-env.yaml
#   kubectl get pods -n production -w  # Watch CrashLoopBackOff

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  namespace: production
  labels:
    app: demo-api
    incident-type: crashloop
  annotations:
    aegis.io/incident-scenario: "crashloop-missing-env"
    aegis.io/expected-fix: "Add DATABASE_URL and REDIS_URL environment variables"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
        version: v1-broken
    spec:
      containers:
        - name: api
          image: python:3.12-slim
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              pip install fastapi uvicorn --quiet 2>/dev/null
              mkdir -p /app
              cat > /app/main.py << 'EOF'
              import os
              import sys

              # This will FAIL because DATABASE_URL is not set
              required_vars = ["DATABASE_URL", "REDIS_URL"]
              for var in required_vars:
                  if not os.getenv(var):
                      print(f"FATAL: Missing required environment variable: {var}", file=sys.stderr)
                      sys.exit(1)

              print("All checks passed, starting application...")
              EOF
              python /app/main.py
          ports:
            - containerPort: 8000
              name: http
          # INTENTIONALLY MISSING: envFrom with secrets
          # This causes the container to crash on startup
          env:
            - name: LOG_LEVEL
              value: "DEBUG"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      restartPolicy: Always
