# INCIDENT: OOMKilled - Memory Leak Simulation
#
# Scenario: Deploy demo-api with a memory leak that exceeds limits
# Expected: Pod gets OOMKilled after ~30 seconds
#
# AEGIS Expected Detection:
#   Root Cause: Container exceeded memory limits (128Mi)
#   Severity: HIGH
#   Fix: Increase memory limits or fix memory leak in application
#
# Usage:
#   kubectl apply -f oomkill-memory-leak.yaml
#   kubectl get pods -n production -w  # Watch OOMKilled status

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  namespace: production
  labels:
    app: demo-api
    incident-type: oomkill
  annotations:
    aegis.io/incident-scenario: "oomkill-memory-leak"
    aegis.io/expected-fix: "Increase memory limits to 512Mi or fix memory leak"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
        version: v1-oom
    spec:
      containers:
        - name: api
          image: python:3.12-slim
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              pip install fastapi uvicorn --quiet 2>/dev/null
              cat > /app/main.py << 'EOF'
              import os
              import time
              import sys

              print("Starting memory leak simulation...")

              # Simulate memory leak - allocate memory continuously
              leaked_memory = []
              chunk_size = 10 * 1024 * 1024  # 10MB chunks

              while True:
                  print(f"Allocating memory... Current size: {len(leaked_memory) * 10}MB")
                  leaked_memory.append(bytearray(chunk_size))
                  time.sleep(2)  # Gradual leak
              EOF
              python /app/main.py
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: DATABASE_URL
              value: "postgresql://demo:demo123@demo-db:5432/demoapp"  # pragma: allowlist secret - Demo credentials for incident simulation
            - name: REDIS_URL
              value: "redis://demo-redis:6379/0"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              # INTENTIONALLY LOW: Will trigger OOMKill
              memory: "128Mi"
              cpu: "100m"
      restartPolicy: Always
