# Demo Redis - Cache Layer
# Simple Redis instance for caching and job queues

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-redis
  namespace: production
  labels:
    app: demo-redis
    app.kubernetes.io/name: demo-redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: aegis-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-redis
  template:
    metadata:
      labels:
        app: demo-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: redis
          command:
            - redis-server
            - --maxmemory
            - "64mb"
            - --maxmemory-policy
            - allkeys-lru
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: demo-redis
  namespace: production
  labels:
    app: demo-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: demo-redis
