# Demo Worker - Background Job Processor
# Simulates async task processing with intentional failure points

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-worker
  namespace: production
  labels:
    app: demo-worker
    app.kubernetes.io/name: demo-worker
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: aegis-demo
  annotations:
    aegis.io/auto-remediate: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-worker
  template:
    metadata:
      labels:
        app: demo-worker
        version: v1
    spec:
      containers:
        - name: worker
          image: python:3.12-slim
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              pip install redis --quiet
              cat > /app/worker.py << 'EOF'
              import os
              import time
              import random
              import signal
              import sys

              # Validate required env vars
              redis_url = os.getenv("REDIS_URL")
              if not redis_url:
                  print("ERROR: Missing REDIS_URL environment variable", file=sys.stderr)
                  sys.exit(1)

              print(f"Worker starting with REDIS_URL: {redis_url[:20]}...")

              def signal_handler(sig, frame):
                  print("Graceful shutdown initiated")
                  sys.exit(0)

              signal.signal(signal.SIGTERM, signal_handler)
              signal.signal(signal.SIGINT, signal_handler)

              # Main worker loop
              job_count = 0
              while True:
                  job_count += 1
                  print(f"Processing job #{job_count}")
                  # Simulate job processing
                  time.sleep(random.uniform(1, 3))
                  print(f"Job #{job_count} completed")
              EOF
              python /app/worker.py
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: demo-api-secrets
                  key: REDIS_URL
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
      restartPolicy: Always
